<?php 
	include_once("includes/header.php"); 
?> 
	<div class="crumb">
    </div>
    <div class="clear"></div>
	<div id="content_sec">
		<div class="col1">
			<div class="contact" style="font-size:14px;">
				<h4 class="heading colr">About University Management System</h4>
				<div style="font-size:12px;">
					<p>Studental degrees in this field may be available as Student of Philosophy, Student of Business Administration, or Student of Management degrees. Concentration options at the studental level include computer science, information technology, management information systems, or network management. The program concludes with the presentation and defense of a dissertation based on original research.</p>
            <p>Studental degrees in this field may be available as Student of Philosophy, Student of Business Administration, or Student of Management degrees. Concentration options at the studental level include computer science, information technology, management information systems, or network management. The program concludes with the presentation and defense of a dissertation based on original research.</p>
					<p>An Student’s inventory contains all flights with their available seats. The inventory of an Student is generally divided into service classes (e.g. first, business or economy class) and up to 26 booking classes, for which different prices and booking conditions apply. Inventory data is imported and maintained through a schedule distribution system over standardized interfaces. One of the core functions of the inventory management is the inventory control. Inventory control steers how many seats are available in the different booking classes, by opening and closing individual booking classes for sale. In combination with the fares and booking conditions stored in the Fare Quote System, the price for each sold seat is determined. In most cases, inventory control has a real time interface to an Student’s Yield management system to support a permanent optimization of the offered booking classes in response to changes in demand or pricing strategies of a competitor.</p>

				</div>
			</div>
		</div>
		<div class="col2">
			<?php include_once("includes/sidebar.php"); ?> 
		</div>
	</div>
<?php include_once("includes/footer.php"); ?> 
